export const dias = [
  {
    value: "",
    label: "Ninguno",
  },
  {
    value: "Lunes",
    label: "Lunes",
  },
  {
    value: "Martes",
    label: "Martes",
  },
  {
    value: "Miercoles",
    label: "Miercoles",
  },
  {
    value: "Jueves",
    label: "Jueves",
  },
  {
    value: "Viernes",
    label: "Viernes",
  },
];

export const comunas = [
  { value: "", label: "Ninguna" },
  { value: "Puente Alto", label: "Puente Alto" },
  { value: "Cerrillos", label: "Cerrillos" },
  { value: "Cerro Navia", label: "Cerro Navia" },
  { value: "Conchalí", label: "Conchalí" },
  { value: "El Bosque", label: "El Bosque" },
  { value: "Estación Central", label: "Estación Central" },
  { value: "Huechuraba", label: "Huechuraba" },
  { value: "Independencia", label: "Independencia" },
  { value: "La Cisterna", label: "La Cisterna" },
  { value: "La Florida", label: "La Florida" },
  { value: "La Granja", label: "La Granja" },
  { value: "La Pintana", label: "La Pintana" },
  { value: "La Reina", label: "La Reina" },
  { value: "Las Condes", label: "Las Condes" },
  { value: "Lo Barnechea", label: "Lo Barnechea" },
  { value: "Lo Espejo", label: "Lo Espejo" },
  { value: "Lo Prado", label: "Lo Prado" },
  { value: "Macul", label: "Macul" },
  { value: "Maipú", label: "Maipú" },
  { value: "Ñuñoa", label: "Ñuñoa" },
  { value: "Pedro Aguirre Cerda", label: "Pedro Aguirre Cerda" },
  { value: "Peñalolén", label: "Peñalolén" },
  { value: "Providencia", label: "Providencia" },
  { value: "Pudahuel", label: "Pudahuel" },
  { value: "Quilicura", label: "Quilicura" },
  { value: "Quinta Normal", label: "Quinta Normal" },
  { value: "Recoleta", label: "Recoleta" },
  { value: "Renca", label: "Renca" },
  { value: "San Joaquín", label: "San Joaquín" },
  { value: "San Miguel", label: "San Miguel" },
  { value: "San Ramón", label: "San Ramón" },
  { value: "Santiago", label: "Santiago" },
  { value: "Vitacura", label: "Vitacura" },
];
export const titlesTable = [
  { label: "Nombre", showOrderBy: false },
  { label: "Dirección", showOrderBy: false },
  { label: "Comuna", showOrderBy: true },
  { label: "Telefono", showOrderBy: true },
  { label: "Email", showOrderBy: true },
  { label: "Dia de Mantención", showOrderBy: true },
  { label: "Valor Mantención", showOrderBy: true },
  { label: "Acciones", showOrderBy: false },
];

export const tiposPiscinasMaterial = [
  { value: "Fibra de Vidrio", label: "Fibra de Vidrio" },
  { value: "Pintura", label: "Pintura" },
  { value: "Concreto en Bruto", label: "Concreto en Bruto" },
  { value: "Marble Dust", label: "Marble Dust" },
  { value: "Diamond Brite", label: "Diamond Brite" },
  { value: "Vinilo", label: "Vinilo" },
  { value: "Azulejo", label: "Azulejo" },
  { value: "Mosaico", label: "Mosaico" },
  { value: "Cemento Liso", label: "Cemento Liso" },
  { value: "Piedra Natural", label: "Piedra Natural" },
  { value: "Hormigón", label: "Hormigón" },
];
